# Prometheus Configuration
# Scrapes metrics from application services and exporters

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "amazcope"
    environment: "production"

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - 'alertmanager:9093'

# Load rules once and periodically evaluate them
# rule_files:
#   - "alerts/*.yml"
#   - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          service: "prometheus"

  # FastAPI Application Metrics
  - job_name: "api"
    static_configs:
      - targets: ["api:8000"]
        labels:
          service: "api"
          app: "amazcope"
    metrics_path: "/metrics"
    scrape_interval: 15s

  # Redis Exporter Metrics
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
        labels:
          service: "redis"
          app: "amazcope"

  # PostgreSQL Exporter Metrics
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          service: "postgres"
          app: "amazcope"

  # Flower Metrics (Dragatiq monitoring)
  - job_name: "flower"
    static_configs:
      - targets: ["flower:5555"]
        labels:
          service: "flower"
          app: "amazcope"
    metrics_path: "/metrics"
    scrape_interval: 30s
