"""empty message

Revision ID: 2821cc1df801
Revises: 5547a336c530
Create Date: 2025-10-23 13:13:52.841890

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2821cc1df801"
down_revision: str | Sequence[str] | None = "5547a336c530"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_suggestion_actions_id"), table_name="suggestion_actions")
    op.drop_index(op.f("ix_suggestion_actions_suggestion_id"), table_name="suggestion_actions")
    op.drop_table("suggestion_actions")
    op.drop_index(op.f("ix_suggestions_id"), table_name="suggestions")
    op.drop_table("suggestions")
    op.alter_column(
        "categories",
        "category_id",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
        existing_comment="Amazon category ID",
    )
    op.add_column(
        "notifications",
        sa.Column(
            "notification_type",
            sa.String(length=50),
            nullable=False,
            comment="Type of notification (e.g., 'price_change', 'system')",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "notification_type")
    op.alter_column(
        "categories",
        "category_id",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
        existing_comment="Amazon category ID",
    )
    op.create_table(
        "suggestions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("reasoning", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("product_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "priority",
            postgresql.ENUM("low", "medium", "high", name="suggestionpriority"),
            server_default=sa.text("'medium'::suggestionpriority"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "category",
            postgresql.ENUM("pricing", "content", "tracking", name="suggestioncategory"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending", "reviewed", "implemented", "rejected", name="suggestionstatus"
            ),
            server_default=sa.text("'pending'::suggestionstatus"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("reviewed_by_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("reviewed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column(
            "ai_model",
            sa.VARCHAR(length=100),
            server_default=sa.text("'gpt-4'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "confidence_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column(
            "estimated_impact",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
            comment="Record last update timestamp",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name="suggestions_product_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name="suggestions_reviewed_by_id_fkey",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="suggestions_pkey"),
        comment="AI-generated product optimization suggestions",
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("ix_suggestions_id"), "suggestions", ["id"], unique=False)
    op.create_table(
        "suggestion_actions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("suggestion_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "action_type",
            postgresql.ENUM(
                "update_price",
                "update_title",
                "update_description",
                "update_brand",
                "update_category",
                "adjust_price_threshold",
                "adjust_bsr_threshold",
                "toggle_tracking",
                name="actiontype",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("target_field", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("current_value", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("proposed_value", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("reasoning", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("impact_description", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("pending", "reviewed", "applied", "rejected", name="actionstatus"),
            server_default=sa.text("'pending'::actionstatus"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("reviewed_by_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("reviewed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("applied_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("applied_by_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("application_result", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
            comment="Record last update timestamp",
        ),
        sa.ForeignKeyConstraint(
            ["applied_by_id"],
            ["users.id"],
            name=op.f("suggestion_actions_applied_by_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name=op.f("suggestion_actions_reviewed_by_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["suggestion_id"],
            ["suggestions.id"],
            name=op.f("suggestion_actions_suggestion_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("suggestion_actions_pkey")),
        comment="Specific actions to implement optimization suggestions",
    )
    op.create_index(
        op.f("ix_suggestion_actions_suggestion_id"),
        "suggestion_actions",
        ["suggestion_id"],
        unique=False,
    )
    op.create_index(op.f("ix_suggestion_actions_id"), "suggestion_actions", ["id"], unique=False)
    # ### end Alembic commands ###
